version: '3'
services:
  api:
    container_name: astor-api
    restart: always
    image: node:20.11.0
    working_dir: /usr/src/app
    command: bash -c "yarn install && yarn start:dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
